### ISSUE TITLE
Secure user registration

### ISSUE THREAD

**Issue by Sabine-Justilien** [embrace-call-for-code/fairchange#41]
### Background on the problem the feature will solve/improved user experience
Users of the application will be required to log-in ahead of accessing the application's capabilities. 

### Describe the solution you'd like
As an upstander / contacted person I can securely register for the platform, knowing my identity will be privacy protected. 

### Tasks 

- [ ]  create authentication protocol
         - [ ]  investigate IBM AppID 
- [ ]  create authorization protocol
- [ ] User journey/Technical requirements session

_TBD_

### Technical requirements
- Registration DB 
- Password protection (MFA) 
- SSO (?)

### Roles Required
- React
- React Native
- User authorisation (e.g. https://auth0.com/blog/complete-guide-to-react-user-authentication/)

### Acceptance Criteria 
- A user can sign up with an email address or social log in
- They are able to set a password for their account use
- They are able to retrieve their email, username, or password if forgotten

**Comment by Sabine-Justilien** [comment]
Need to investigate

- Define what permissions/authorizations are required for different parts of the app
- Authorizations will look differently for various users: witness to a contact (recorder), contacted person being recorded, administrator (NGO, accountability agency, evidentiary review).
- Unregistration process
- [IBM App ID](https://www.ibm.com/cloud/app-id) v [Auth0](https://auth0.com/?utm_content=branded-homepage&utm_source=google&utm_medium=cpc&utm_term=-g-auth0&utm_campaign=amer-usa-search-branded&utm_id=go_cmp-12865209972_adg-123980878280_ad-517398498153_kwd-331982174580_dev-c_ext-_prd-_mca-_sig-Cj0KCQiAys2MBhDOARIsAFf1D1dHIvCi89grhe2vmt0CfmCacLzLou661xTKtAa1Lw69G3Yk6qfi17MaAtLaEALw_wcB&gclid=Cj0KCQiAys2MBhDOARIsAFf1D1dHIvCi89grhe2vmt0CfmCacLzLou661xTKtAa1Lw69G3Yk6qfi17MaAtLaEALw_wcB)
